In [28]:
import numpy as arrayapi
import numpy as np

In [2]:
A = arrayapi.arange(10)

In [3]:
A

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arrayapi.transpose(A)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
A.T

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
A.transpose()


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
A = A.reshape((5,2))

In [15]:
A

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
arrayapi.identity(A.size)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [20]:
A = arrayapi.array([
       [2.9 , 2.  , 2.4 ],
       [3.95, 3.95, 4.65],
       [2.1 , 2.5 , 2.7 ],
       [1.9 , 4.85, 3.25],
       [3.35, 3.45, 3.45]])


In [21]:
A.reshape((15,))

array([2.9 , 2.  , 2.4 , 3.95, 3.95, 4.65, 2.1 , 2.5 , 2.7 , 1.9 , 4.85,
       3.25, 3.35, 3.45, 3.45])

In [27]:
A.transpose((3,5))

AxisError: axis 3 is out of bounds for array of dimension 2

In [35]:
Z = np.array([[[[0.95]]],
       [[[2.55]]],
       [[[0.45]]]],axes=(2,3))

TypeError: array() got an unexpected keyword argument 'axes'

In [31]:
Z.shape

(3, 1, 1, 1)

In [34]:
np.transpose(Z,(2,3))

ValueError: axes don't match array

In [36]:
x = np.ones((480, 640, 3))
np.transpose(x, (1, 0, 2)).shape

(640, 480, 3)

In [38]:
x.shape

(480, 640, 3)

In [45]:
T = np.array([[[1.95]],
       [[2.7 ]],
       [[3.75]]])
T.shape

(3, 1, 1)

In [46]:
T.transpose((1,0,2))


array([[[1.95],
        [2.7 ],
        [3.75]]])

In [47]:
M = np.array([[[[0.95]]],
       [[[2.55]]],
       [[[0.45]]]])

In [48]:
M.shape

(3, 1, 1, 1)

In [49]:
T = np.array([[[[0.95]]],
       [[[2.55]]],
       [[[0.45]]]])

In [50]:
T.shape

(3, 1, 1, 1)

In [52]:
M > 1


array([[[[False]]],


       [[[ True]]],


       [[[False]]]])

In [54]:
M = np.arange(14)


In [58]:
M = np.random.rand((6))
1/M

array([0.1058369 , 0.15361598, 0.79991649, 0.53858418, 0.23227103,
       0.37854379])

In [59]:
(5,4) > (4,5)

True